#!/usr/bin/env bash
# prepare-pr.sh: strip forbidden paths from the current branch into a
# sibling --for-<target> branch, so you can open a PR against <target>
# without scaffold-check.yml rejecting it.
#
# Usage:
#   ./scripts/prepare-pr.sh <target-branch>
#
# Example:
#   ./scripts/prepare-pr.sh dev
#
# Result:
#   - Creates a new branch named `<current-branch>--for-<target>`
#   - Force-resets it to the current commit
#   - Removes all files matching the `forbidden_paths` of <target>
#     defined in .scaffold/protected-paths.yml
#   - Commits the removal
#   - Pushes (with --force-with-lease) so subsequent runs overwrite cleanly
#   - Prints the `gh pr create` command you should run

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <target-branch>" >&2
  exit 2
fi

TARGET="$1"
CONFIG=".scaffold/protected-paths.yml"
CURRENT=$(git branch --show-current)

if [ -z "${CURRENT}" ]; then
  echo "Error: not on any branch (detached HEAD?)" >&2
  exit 1
fi

if [ ! -f "${CONFIG}" ]; then
  echo "Error: ${CONFIG} not found. Are you in the repo root?" >&2
  exit 1
fi

if ! command -v yq >/dev/null 2>&1; then
  echo "Error: yq is required. Install with: brew install yq" >&2
  exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "Error: working tree is not clean. Commit or stash first." >&2
  exit 1
fi

NEW_BRANCH="${CURRENT}--for-${TARGET}"

# Read forbidden_paths for target
mapfile -t FORBIDDEN < <(yq ".${TARGET}.forbidden_paths[]" "${CONFIG}" 2>/dev/null || true)
if [ "${#FORBIDDEN[@]}" -eq 0 ]; then
  echo "No forbidden_paths defined for '${TARGET}' in ${CONFIG}. Nothing to strip."
  echo "You can PR directly: gh pr create --base ${TARGET} --head ${CURRENT}"
  exit 0
fi

echo "Target branch:   ${TARGET}"
echo "Current branch:  ${CURRENT}"
echo "Sibling branch:  ${NEW_BRANCH}"
echo ""
echo "Will strip the following paths:"
for p in "${FORBIDDEN[@]}"; do echo "  - ${p}"; done
echo ""

# Create or reset the sibling branch
if git rev-parse --verify "${NEW_BRANCH}" >/dev/null 2>&1; then
  git branch -D "${NEW_BRANCH}"
fi
git checkout -b "${NEW_BRANCH}"

# Remove each forbidden path
REMOVED=0
for path in "${FORBIDDEN[@]}"; do
  # Trim slashes; git rm handles dirs with -r
  trimmed=$(echo "${path}" | sed 's:/*$::')
  if [ -e "${trimmed}" ]; then
    git rm -rf --quiet "${trimmed}" || true
    REMOVED=1
  fi
done

if [ "${REMOVED}" -eq 0 ]; then
  echo "No forbidden paths existed on this branch. Nothing to commit."
  git checkout "${CURRENT}"
  git branch -D "${NEW_BRANCH}"
  echo ""
  echo "You can PR directly: gh pr create --base ${TARGET} --head ${CURRENT}"
  exit 0
fi

git commit -m "$(cat <<EOF
chore(prepare-pr): strip ${TARGET}-forbidden paths

Generated by scripts/prepare-pr.sh ${TARGET} from ${CURRENT}.
Stripped paths (per .scaffold/protected-paths.yml):
$(for p in "${FORBIDDEN[@]}"; do echo "  - ${p}"; done)
EOF
)"

# Push the sibling branch
git push --force-with-lease origin "${NEW_BRANCH}"

echo ""
echo "✅ Sibling branch '${NEW_BRANCH}' is on origin with forbidden paths removed."
echo ""
echo "Next: open the PR with:"
echo "  gh pr create --base ${TARGET} --head ${NEW_BRANCH} \\"
echo "    --title '<your title>' \\"
echo "    --body '<your description>'"
echo ""
echo "Returning to '${CURRENT}'..."
git checkout "${CURRENT}"
